name: Python CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt
          pip install flake8 pylint

      - name: Проверка кода (flake8)
        run: |
          flake8 . || true

      - name: Проверка кода (pylint)
        run: |
          pylint app.py || true

      - name: Запуск тестов
        run: |
          python -m unittest discover
